[package]
name = "testmacro"
version = "0.1.0"
authors = ["yhql <yhql@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"